//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesWcf.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_ObtCtes", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.DataContract")]
    [System.SerializableAttribute()]
    public partial class dc_ObtCtes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelegacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Delegacion {
            get {
                return this.DelegacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DelegacionField, value) != true)) {
                    this.DelegacionField = value;
                    this.RaisePropertyChanged("Delegacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dc_VerInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfService1.DataContract")]
    [System.SerializableAttribute()]
    public partial class dc_VerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnioPublicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloOriginalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnioPublicacion {
            get {
                return this.AnioPublicacionField;
            }
            set {
                if ((this.AnioPublicacionField.Equals(value) != true)) {
                    this.AnioPublicacionField = value;
                    this.RaisePropertyChanged("AnioPublicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Editorial {
            get {
                return this.EditorialField;
            }
            set {
                if ((object.ReferenceEquals(this.EditorialField, value) != true)) {
                    this.EditorialField = value;
                    this.RaisePropertyChanged("Editorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opcion {
            get {
                return this.OpcionField;
            }
            set {
                if ((object.ReferenceEquals(this.OpcionField, value) != true)) {
                    this.OpcionField = value;
                    this.RaisePropertyChanged("Opcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TituloOriginal {
            get {
                return this.TituloOriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloOriginalField, value) != true)) {
                    this.TituloOriginalField = value;
                    this.RaisePropertyChanged("TituloOriginal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtCtes", ReplyAction="http://tempuri.org/IService1/ObtCtesResponse")]
        ClientesWcf.WS.dc_ObtCtes[] ObtCtes(int id, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtCtes", ReplyAction="http://tempuri.org/IService1/ObtCtesResponse")]
        System.Threading.Tasks.Task<ClientesWcf.WS.dc_ObtCtes[]> ObtCtesAsync(int id, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registro", ReplyAction="http://tempuri.org/IService1/RegistroResponse")]
        bool Registro(string Opcion, string Titulo, string TituloOriginal, string Autor, string Genero, string Editorial, int AnioPublicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registro", ReplyAction="http://tempuri.org/IService1/RegistroResponse")]
        System.Threading.Tasks.Task<bool> RegistroAsync(string Opcion, string Titulo, string TituloOriginal, string Autor, string Genero, string Editorial, int AnioPublicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerInfo", ReplyAction="http://tempuri.org/IService1/VerInfoResponse")]
        ClientesWcf.WS.dc_VerInfo[] VerInfo(string opcion, string titulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/VerInfo", ReplyAction="http://tempuri.org/IService1/VerInfoResponse")]
        System.Threading.Tasks.Task<ClientesWcf.WS.dc_VerInfo[]> VerInfoAsync(string opcion, string titulo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientesWcf.WS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientesWcf.WS.IService1>, ClientesWcf.WS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientesWcf.WS.dc_ObtCtes[] ObtCtes(int id, string cliente) {
            return base.Channel.ObtCtes(id, cliente);
        }
        
        public System.Threading.Tasks.Task<ClientesWcf.WS.dc_ObtCtes[]> ObtCtesAsync(int id, string cliente) {
            return base.Channel.ObtCtesAsync(id, cliente);
        }
        
        public bool Registro(string Opcion, string Titulo, string TituloOriginal, string Autor, string Genero, string Editorial, int AnioPublicacion) {
            return base.Channel.Registro(Opcion, Titulo, TituloOriginal, Autor, Genero, Editorial, AnioPublicacion);
        }
        
        public System.Threading.Tasks.Task<bool> RegistroAsync(string Opcion, string Titulo, string TituloOriginal, string Autor, string Genero, string Editorial, int AnioPublicacion) {
            return base.Channel.RegistroAsync(Opcion, Titulo, TituloOriginal, Autor, Genero, Editorial, AnioPublicacion);
        }
        
        public ClientesWcf.WS.dc_VerInfo[] VerInfo(string opcion, string titulo) {
            return base.Channel.VerInfo(opcion, titulo);
        }
        
        public System.Threading.Tasks.Task<ClientesWcf.WS.dc_VerInfo[]> VerInfoAsync(string opcion, string titulo) {
            return base.Channel.VerInfoAsync(opcion, titulo);
        }
    }
}
